#!/bin/bash

export PATH=/sbin:/bin:/usr/sbin:/usr/bin
RUNNING=`ps xa | grep amavislogwatch | grep perl | wc -l`
test $RUNNING -gt 0 && killall amavislogwatch
sleep 20
DATE=`date -d now '+%s'`
EXP=`expr $DATE + 7200`
(for IPADDR in `iptables -L AMAVISFW -n | awk '{print $4}' | grep '^[1-9]' | grep -v / | sort -u` ; do
  grep -w "$IPADDR" /var/tmp/amavislogwatch-ckp >/dev/null && continue
  echo "$IPADDR 1:1:${DATE}:${EXP}"
done) > /var/tmp/amavislogwatch-ckp.old
cat /var/tmp/amavislogwatch-ckp.old >> /var/tmp/amavislogwatch-ckp
/sbin/iptables -F AMAVISFW
/usr/local/sbin/amavislogwatch --checkpoint=/var/tmp/amavislogwatch-ckp --conndelay=7200 --firewall=AMAVISFW --logpolicy=no --iptablesargs="-m tcp -p tcp -m state --state NEW"
exit 0
